package com.buildme.service;

import com.buildme.entity.SessionCommit;
import com.buildme.repository.SessionCommitRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

/**
 * SessionCommit Service - Business logic for session commits
 */
@Service
@Slf4j
@RequiredArgsConstructor
@Transactional
public class SessionCommitService {

    private final SessionCommitRepository sessionCommitRepository;
    private final ClaudeService claudeService;
    private final UserProfileService userProfileService;
    private final DsaService dsaService;

    /**
     * Generate session commit
     */
    public SessionCommit generateCommit(List<String> recentProgress, List<String> openLoops,
                                       boolean autoGenerated) {
        String level = userProfileService.getUserLevel();
        int dsaStreak = dsaService.getStreak30Days();
        int cheveningHours = userProfileService.getCheveningHours();

        String recentProgressStr = String.join("; ", recentProgress);

        String commitJson = claudeService.generateSessionCommit(
            level, "1", recentProgressStr, dsaStreak, cheveningHours, openLoops
        );

        if (commitJson == null) {
            return null;
        }

        SessionCommit commit = SessionCommit.builder()
            .copyablePrompt(commitJson)
            .autoGenerated(autoGenerated)
            .generatedAt(LocalDateTime.now())
            .build();

        return sessionCommitRepository.save(commit);
    }

    /**
     * Get latest commit
     */
    public Optional<SessionCommit> getLatest() {
        return sessionCommitRepository.findTopByOrderByGeneratedAtDesc();
    }

    /**
     * Save commit
     */
    public SessionCommit save(SessionCommit commit) {
        return sessionCommitRepository.save(commit);
    }
}

