package com.buildme.controller;

import com.buildme.dto.ApiResponse;
import com.buildme.entity.SessionCommit;
import com.buildme.service.SessionCommitService;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.Map;

@RestController
@RequestMapping("/api/commit")
@RequiredArgsConstructor
public class CommitController {

    private final SessionCommitService sessionCommitService;

    @PostMapping("/generate")
    public ResponseEntity<ApiResponse<Map<String,Object>>> generate(@RequestParam(defaultValue = "false") boolean autoGenerated) {
        SessionCommit commit = sessionCommitService.generateCommit(null, null, autoGenerated);
        if (commit == null) return ResponseEntity.ok(ApiResponse.success(Map.of("commit", "{}")));
        return ResponseEntity.ok(ApiResponse.success(Map.of("commit", commit.getCopyablePrompt(), "generatedAt", commit.getGeneratedAt())));
    }

    @GetMapping("/latest")
    public ResponseEntity<ApiResponse<SessionCommit>> latest() {
        var commit = sessionCommitService.getLatest();
        return commit.map(sessionCommit -> ResponseEntity.ok(ApiResponse.success(sessionCommit))).orElseGet(() -> ResponseEntity.noContent().build());
    }
}

