package com.buildme.entity;

import jakarta.persistence.*;
import lombok.*;
import java.time.*;

@Entity
@Table(name = "session_commits")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class SessionCommit {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    @Column(columnDefinition = "TEXT")
    private String summary;

    @Column(columnDefinition = "TEXT")
    private String openLoopsJson;

    @Column(columnDefinition = "TEXT")
    private String nextStepsJson;

    @Column(columnDefinition = "TEXT", nullable = false)
    private String copyablePrompt;

    private boolean autoGenerated;
    private LocalDateTime generatedAt;
}

